### ISSUE TITLE
403 forbidden

### ISSUE THREAD

**Issue by Radik24** [nightf0rc3/vodafone-station#9]
Hi, I'm getting Forbidden from vodafone-station. I'm sure I have correct user,password, url and I'm not logged in from browser.

```
Error: Received unexpected message from server: <?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
         "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
 <head>
  <title>403 - Forbidden</title>
 </head>
 <body>
  <h1>403 - Forbidden</h1>
 </body>
</html>
```

I have Vodafone Docsis 3.1

Any ideas what can be wrong? Thanks!

**Comment by amki** [comment]
I just had the same issue, my box wants the login data POSTed and not PUT to the webserver. I fixed the login process in https://github.com/nightf0rc3/vodafone-station/pull/12
